apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-cluster-{{ .Values.global.zoneB }}
  labels:
    app: redis-cluster
spec:
  serviceName: redis-cluster
  replicas: 3
  selector:
    matchLabels:
      app: redis-cluster-{{ .Release.Name }}
      region: {{ .Values.global.region | quote }}
      zone: {{ .Values.global.zoneB | quote }}
  template:
    metadata:
      labels:
        app: redis-cluster-{{ .Release.Name }}
        antiaffinity: redis-node
        region: {{ .Values.global.region | quote }}
        zone: {{ .Values.global.zoneB | quote }}
    spec:
      # ゾーンを指定
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: {{ .Values.global.zoneB | quote }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: antiaffinity
                  operator: In
                  values:
                  - redis-node
              topologyKey: kubernetes.io/hostname
      containers:
      - name: redis
        image: redis:5.0.5
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        command: ["/conf/fix-ip.sh", "redis-server", "/conf/redis.conf"]
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 20
          periodSeconds: 3
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: conf
          mountPath: /conf
          readOnly: false
        - name: data
          mountPath: /data
          readOnly: false
      volumes:
      - name: conf
        configMap:
          name: redis-cluster-{{ .Release.Name }}
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: redis-cluster
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 1G
