apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-{{ .Release.Name }}-{{ .Values.global.zoneB }}-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/redis-{{ .Release.Name }}-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - {{ .Values.global.zoneB }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-{{ .Release.Name }}-{{ .Values.global.zoneB }}-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/redis-{{ .Release.Name }}-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - {{ .Values.global.zoneB }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-{{ .Release.Name }}-{{ .Values.global.zoneB }}-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/redis-{{ .Release.Name }}-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - {{ .Values.global.zoneB }}

